// client-angular/src/app/shared/navbar/navbar.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

@Component({
    selector: 'app-navbar',
    templateUrl: './navbar.component.html',
    styleUrls: ['./navbar.component.css']
})
export class NavbarComponent implements OnInit {

    constructor() { }

    ngOnInit() {
    }
}

<nav class="navbar navbar-expand-md navbar-dark">
    <div class="container">
        <a
            routerLink="/"
            class="navbar-brand"
        >Movie Catalog</a>
        <button
            type="button"
            class="navbar-toggler navbar-toggler-right"
            aria-controls=".navbar-collapse"
            aria-expanded="false"
            aria-label="Toggle navigation"
            data-target=".navbar-collapse"
            data-toggle="collapse"
        >
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item dropdown">
                    <a
                        routerLink="/"
                        class="nav-link dropdown-toggle"
                        aria-expanded="false"
                        aria-haspopup="true"
                        data-toggle="dropdown"
                        role="button"
                    >Movies</a>
                    <div class="dropdown-menu">
                        <a
                            routerLink="/"
                            class="dropdown-item"
                        >All Movies</a>
                        <a
                            routerLink="/movies/create"
                            class="dropdown-item"
                        >Create Movie</a>
                    </div>
                </li>
            </ul>
            <ul
                class="navbar-nav"
                id="navbarSupportedContent"
            >
                <li class="nav-item dropdown">
                    <a
                        routerLink="/"
                        class="nav-link dropdown-toggle"
                        aria-expanded="false"
                        aria-haspopup="true"
                        data-toggle="dropdown"
                        role="button"
                    >Admin</a>
                    <div class="dropdown-menu">
                        <a
                            routerLink="/admin/users/all"
                            class="dropdown-item"
                        >All Users</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a
                        routerLink="/"
                        class="nav-link dropdown-toggle"
                        aria-expanded="false"
                        aria-haspopup="true"
                        data-toggle="dropdown"
                        role="button"
                    >My Profile</a>
                    <div class="dropdown-menu">
                        <a
                            routerLink="/"
                            class="dropdown-item"
                        >Edit Details</a>
                        <a
                            routerLink="/"
                            class="dropdown-item"
                        >Edit Password</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a
                        routerLink="/"
                        class="nav-link"
                    >Logout</a>
                </li>
            </ul>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a
                        routerLink="/users/login"
                        class="nav-link"
                    >Login</a>
                </li>
                <li class="nav-item">
                    <a
                        routerLink="/users/register"
                        class="nav-link"
                    >Register</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

// client-react/src/components/shared/Navbar.jsx
import React from 'react'
import { connect } from 'react-redux'
import { Link } from 'react-router-dom'

import usersActions from '../../redux/actions/users-actions'

const Navbar = (props) => {
    const onSignOut = () => {
        props.signOut()
    }
    return (
        <nav className="navbar navbar-expand-md navbar-dark">
            <div className="container">
                <Link
                    to="/"
                    className="navbar-brand"
                >Movie Catalog
                </Link>
                <button
                    type="button"
                    className="navbar-toggler navbar-toggler-right"
                    aria-controls=".navbar-collapse"
                    aria-expanded="false"
                    aria-label="Toggle navigation"
                    data-target=".navbar-collapse"
                    data-toggle="collapse"
                >
                    <span className="navbar-toggler-icon"></span>
                </button>
                <div className="collapse navbar-collapse">
                    <ul className="navbar-nav mr-auto">
                        <li className="nav-item dropdown">
                            <Link
                                to="/"
                                className="nav-link dropdown-toggle"
                                aria-expanded="false"
                                aria-haspopup="true"
                                data-toggle="dropdown"
                                role="button"
                            >Movies
                            </Link>
                            <div className="dropdown-menu">
                                <Link
                                    to="/"
                                    className="dropdown-item"
                                >All Movies
                                </Link>
                                <Link
                                    to="/movies/create"
                                    className="dropdown-item"
                                >Create Movie
                                </Link>
                            </div>
                        </li>
                    </ul>
                    {props.user.isAuthenticated && (
                        <ul
                            className="navbar-nav"
                            id="navbarSupportedContent"
                        >
                            {props.user.isAdmin && (
                                <li className="nav-item dropdown">
                                    <Link
                                        to="/"
                                        className="nav-link dropdown-toggle"
                                        aria-expanded="false"
                                        aria-haspopup="true"
                                        data-toggle="dropdown"
                                        role="button"
                                    >Admin
                                    </Link>
                                    <div className="dropdown-menu">
                                        <Link
                                            to="/users/all"
                                            className="dropdown-item"
                                        >All Users
                                        </Link>
                                    </div>
                                </li>
                            )}
                            <li className="nav-item dropdown">
                                <Link
                                    to="/"
                                    className="nav-link dropdown-toggle"
                                    aria-expanded="false"
                                    aria-haspopup="true"
                                    data-toggle="dropdown"
                                    role="button"
                                >My Profile
                                </Link>
                                <div className="dropdown-menu">
                                    <Link
                                        to={'/users/edit/details/' + props.user._id}
                                        className="dropdown-item"
                                    >Edit Details
                                    </Link>
                                    <Link
                                        to={'/users/edit/password/' + props.user._id}
                                        className="dropdown-item"
                                    >Edit Password
                                    </Link>
                                </div>
                            </li>
                            <li className="nav-item">
                                <Link
                                    to="/"
                                    className="nav-link"
                                    onClick={onSignOut}
                                >Logout
                                </Link>
                            </li>
                        </ul>
                    )}
                    {!props.user.isAuthenticated && (
                        <ul className="navbar-nav">
                            <li className="nav-item">
                                <Link
                                    to="/users/signin"
                                    className="nav-link"
                                >Login
                                </Link>
                            </li>
                            <li className="nav-item">
                                <Link
                                    to="/users/signup"
                                    className="nav-link"
                                >Register
                                </Link>
                            </li>
                        </ul>
                    )}
                </div>
            </div>
        </nav>
    )
}

const mapDispatchToProps = (dispatch) => {
    return {
        signOut: () => {
            dispatch(usersActions.creators.signOut({}))
        }
    }
}

const mapStateToProps = (state) => {
    return {
        user: state.users.signIn
    }
}

export default connect(mapStateToProps, mapDispatchToProps)(Navbar)
