// client-angular/src/app/users/user-form/user-form.component.ts
import { Component, OnInit, Input, Injector, OnChanges } from '@angular/core';
import { AbstractControl, FormBuilder, FormGroup, Validators } from '@angular/forms';

import { AbstractComponent } from '../shared/abstract.component';

const fbPass = {
    minlength: 'Password should be min 6 symbols long!',
    required: 'Password is required!',
    validators: Validators.compose(
        [Validators.minLength(6), Validators.required]
    )
};

const fbProps = {
    email: {
        email: 'Invalid email!',
        required: 'Email is required!',
        validators: Validators.compose(
            [Validators.email, Validators.required]
        )
    },
    password: fbPass,
    passwordCurrent: fbPass,
    passwordNew: fbPass,
    passwordRepeat: {
        mismatch: 'Passwords do not match!',
        validators: null
    },
    passwordRepeatNew: {
        mismatch: 'Passwords do not match!',
        validators: null
    },
    username: {
        required: 'Username is required!',
        validators: Validators.compose(
            [Validators.required]
        )
    }
};

@Component({
    selector: 'app-user-form',
    templateUrl: './user-form.component.html',
    styleUrls: ['./user-form.component.css']
})
export class UserFormComponent extends AbstractComponent implements OnInit, OnChanges {
    @Input('attr') attr: any;
    @Input('errors') errors: any;
    @Input('formModel') formModel: Object;
    @Input('isFormReady') isFormReady: boolean;
    @Input('isSubmitting') isSubmitting: boolean;
    @Input('onSubmitHandler') onSubmitHandler: Function;
    private fbGroup = {};
    private userForm: FormGroup;

    constructor(
        private fb: FormBuilder,
        public injector: Injector
    ) {
        super(injector);
    }

    ngOnInit() { }

    ngOnChanges() {
        // Wait for parent to collect data from service
        if (!this.isFormReady) {
            return;
        }

        this.groupFormModelPropsFromParent();

        this.userForm = this.fb.group(this.fbGroup);

        this.setPasswordValidators();

        this.subscribeToValueChangesAndValidate();
    }

    cancel() {
        this.location.back();
    }

    private groupFormModelPropsFromParent() {
        Object.keys(this.formModel)
            .forEach(key => {
                if (!fbProps.hasOwnProperty(key)) {
                    return;
                }
                this.fbGroup[key] = [
                    {
                        value: this.formModel[key],
                        disabled: this.attr.isFieldDisabled
                    },
                    fbProps[key].validators
                ];
            });
    }

    private passwordMatchValidator(c: AbstractControl, other: AbstractControl) {
        if (c.value !== other.value) {
            return { mismatch: true };
        }

        return null;
    }

    private setPasswordValidators() {
        if (this.userForm.get('passwordRepeat')) {
            this.userForm.get('passwordRepeat')
                .setValidators(Validators.compose([
                    this.passwordMatchValidator.bind(this, this.userForm.get('password')),
                    Validators.required
                ]));
        } else if (this.userForm.get('passwordRepeatNew')) {
            this.userForm.get('passwordRepeatNew')
                .setValidators(Validators.compose([
                    this.passwordMatchValidator.bind(this, this.userForm.get('passwordNew')),
                    Validators.required
                ]));
        }
    }

    private subscribeToValueChangesAndValidate() {
        Object.keys(this.userForm.controls).forEach(name => {
            const fieldControl = this.userForm.get(name);
            fieldControl.valueChanges.subscribe((value) => {
                if (name === 'password' && this.userForm.get('passwordRepeat')) {
                    this.userForm.get('passwordRepeat').updateValueAndValidity();
                } else if (name === 'passwordNew' && this.userForm.get('passwordRepeatNew')) {
                    this.userForm.get('passwordRepeatNew').updateValueAndValidity();
                }
                if (!fieldControl.valid) {
                    this.errors[name] = Object.keys(fieldControl.errors)
                        .map(key => fbProps[name][key]);
                } else {
                    this.errors[name] = null;
                }
            });
        });
    }
}

<section class="d-flex flex-row justify-content-center">
    <article class="col-4">
        <h1 class="text-center">{{attr.title}}</h1>
        <form
            *ngIf="userForm"
            [formGroup]="userForm"
            (ngSubmit)="onSubmitHandler(userForm.value)"
        >
            <div
                *ngIf="attr.isFieldVisibleUsername"
                class="col-12 form-group p-0"
            >
                <label
                    class="form-control-label"
                    for="username"
                >Username</label>
                <input
                    formControlName="username"
                    type="text"
                    class="form-control"
                    [class.is-invalid]="userForm.get('username').touched && errors.username"
                    id="username"
                    placeholder="Enter username"
                />
                <div
                    *ngIf="userForm.get('username').touched && errors.username"
                    class="invalid-feedback"
                >{{errors.username ? errors.username : 'Username is Required!'}}</div>
            </div>
            <div
                *ngIf="attr.isFieldVisibleEmail"
                class="col-12 form-group p-0"
            >
                <label
                    class="form-control-label"
                    for="email"
                >Email</label>
                <input
                    formControlName="email"
                    type="email"
                    class="form-control"
                    [class.is-invalid]="userForm.get('email').touched && !userForm.get('email').valid"
                    id="email"
                    placeholder="Enter email"
                />
                <div
                    *ngIf="userForm.get('email').touched && !userForm.get('email').valid"
                    class="invalid-feedback"
                >{{errors.email ? errors.email : 'Email is Required!'}}</div>
            </div>
            <div
                *ngIf="attr.isFieldVisiblePassword"
                class="col-12 form-group p-0"
            >
                <label
                    class="form-control-label"
                    for="password"
                >Password</label>
                <input
                    formControlName="password"
                    type="password"
                    class="form-control"
                    [class.is-invalid]="userForm.get('password').touched && !userForm.get('password').valid"
                    id="password"
                    placeholder="Enter password"
                />
                <div
                    *ngIf="userForm.get('password').touched && !userForm.get('password').valid"
                    class="invalid-feedback"
                >{{errors.password ? errors.password : 'Password is Required!'}}</div>
            </div>
            <div
                *ngIf="attr.isFieldVisiblePasswordCurrent"
                class="col-12 form-group p-0"
            >
                <label
                    class="form-control-label"
                    for="passwordCurrent"
                >Current Password</label>
                <input
                    formControlName="passwordCurrent"
                    type="password"
                    class="form-control"
                    [class.is-invalid]="userForm.get('passwordCurrent').touched && !userForm.get('passwordCurrent').valid"
                    id="passwordCurrent"
                    placeholder="Enter current password"
                />
                <div
                    *ngIf="userForm.get('passwordCurrent').touched && !userForm.get('passwordCurrent').valid"
                    class="invalid-feedback"
                >{{errors.passwordCurrent ? errors.passwordCurrent : 'Password is Required!'}}</div>
            </div>
            <div
                *ngIf="attr.isFieldVisiblePasswordNew"
                class="col-12 form-group p-0"
            >
                <label
                    class="form-control-label"
                    for="passwordNew"
                >New Password</label>
                <input
                    formControlName="passwordNew"
                    type="password"
                    class="form-control"
                    [class.is-invalid]="userForm.get('passwordNew').touched && !userForm.get('passwordNew').valid"
                    id="passwordNew"
                    placeholder="Enter new password"
                />
                <div
                    *ngIf="userForm.get('passwordNew').touched && !userForm.get('passwordNew').valid"
                    class="invalid-feedback"
                >{{errors.passwordNew ? errors.passwordNew : 'Password is Required!'}}</div>
            </div>
            <div
                *ngIf="attr.isFieldVisiblePasswordRepeat"
                class="col-12 form-group p-0"
            >
                <label
                    class="form-control-label"
                    for="passwordRepeat"
                >Repeat Password</label>
                <input
                    formControlName="passwordRepeat"
                    type="password"
                    class="form-control"
                    [class.is-invalid]="userForm.get('passwordRepeat').touched && !userForm.get('passwordRepeat').valid"
                    id="passwordRepeat"
                    placeholder="Repeat password"
                />
                <div
                    *ngIf="userForm.get('passwordRepeat').touched && !userForm.get('passwordRepeat').valid"
                    class="invalid-feedback"
                >{{errors.passwordRepeat ? errors.passwordRepeat : 'Password is Required!'}}</div>
            </div>
            <div
                *ngIf="attr.isFieldVisiblePasswordRepeatNew"
                class="col-12 form-group p-0"
            >
                <label
                    class="form-control-label"
                    for="passwordRepeatNew"
                >Repeat New Password</label>
                <input
                    formControlName="passwordRepeatNew"
                    type="password"
                    class="form-control"
                    [class.is-invalid]="userForm.get('passwordRepeatNew').touched && !userForm.get('passwordRepeatNew').valid"
            
                    id="passwordRepeatNew"
                    placeholder="Repeat new password"
                />
                <div
                    *ngIf="userForm.get('passwordRepeatNew').touched && !userForm.get('passwordRepeatNew').valid"
                    class="invalid-feedback"
                >{{errors.passwordRepeatNew ? errors.passwordRepeatNew : 'Password is Required!'}}</div>
            </div>
            <div
                class="btn-group d-flex"
                role="group"
            >
                <button
                    (click)="cancel()"
                    type="button"
                    class="btn btn-outline-secondary w-100"
                >Cancel</button>
                <button
                    type="submit"
                    class="btn {{attr.btnColor}} w-100"
                    [disabled]="userForm.invalid || isSubmitting"
                >{{attr.btnText}}</button>
            </div>
        </form>
    </article>
</section>

// client-react/src/components/Users/_UserForm.jsx
import React from 'react'
import { Formik, Field as FormikField, Form as FormikForm } from 'formik'
import * as yup from 'yup'

import FieldGroup from '../shared/FieldGroup'

const yupProps = {
    email: yup.string()
        .email('Invalid email!')
        .required('Email is required!')
        .trim(),
    password: yup.string()
        .required('Password is required!'),
    passwordCurrent: yup.string()
        .required('Password is required!'),
    passwordNew: yup.string()
        .required('Password is required!'),
    passwordRepeat: yup.string()
        .oneOf([yup.ref('password')], 'Passwords do not match!')
        .required('Password is required!'),
    passwordRepeatNew: yup.string()
        .oneOf([yup.ref('passwordNew')], 'Passwords do not match!')
        .required('Password is required!'),
    username: yup.string()
        .required('Username is required!')
        .trim()
}

const UserFormTemp = (props) => {
    const yupSchema = {}
    // Configure yup schema based on fomModel keys
    Object.keys(props.formModel).forEach((key) => {
        yupSchema[key] = yupProps[key]
    })

    return (
        <Formik
            enableReinitialize={true}
            initialValues={props.initValues}
            validationSchema={yup.object().shape(yupSchema)}
            onSubmit={
                async (values, { setErrors, setSubmitting }) => {
                    const data = {}
                    Object.keys(props.formModel).forEach((key) => {
                        data[key] = values[key]
                    })

                    try {
                        const id = props.match.params.id
                        let res = null
                        if (!id) {
                            res = await props.onSubmitHandler(data)
                        } else {
                            res = await props.onSubmitHandler(id, data)
                        }

                        if (!res.success) {
                            console.log(res.message)
                            setErrors(res.errors)
                            setSubmitting(false)
                            return
                        }

                        props.history.goBack()
                    } catch (err) {
                        console.log(err)
                    }
                }
            }
            render={({ isSubmitting, values }) => (
                <section className="d-flex flex-row justify-content-center">
                    <article className="col-4">
                        <h1 className="text-center">{props.attr.title}</h1>
                        <FormikForm>
                            {props.attr.isFieldVisibleUsername && (
                                <FormikField
                                    colWidth='col-12'
                                    component={FieldGroup}
                                    componentType='input'
                                    disabled={props.attr.isFieldDisabled}
                                    label='Username'
                                    name='username'
                                    placeholder='Enter username'
                                    required={true}
                                    type='text'
                                    value={values.username}
                                />
                            )}
                            {props.attr.isFieldVisibleEmail && (
                                <FormikField
                                    colWidth='col-12'
                                    component={FieldGroup}
                                    componentType='input'
                                    disabled={props.attr.isFieldDisabled}
                                    label='Email'
                                    name='email'
                                    placeholder='Enter email'
                                    required={true}
                                    type='email'
                                    value={values.email}
                                />
                            )}
                            {props.attr.isFieldVisiblePassword && (
                                <FormikField
                                    colWidth='col-12'
                                    component={FieldGroup}
                                    componentType='input'
                                    disabled={props.attr.isFieldDisabled}
                                    label='Password'
                                    name='password'
                                    placeholder='Enter password'
                                    required={true}
                                    type='password'
                                    value={values.password}
                                />
                            )}
                            {props.attr.isFieldVisiblePasswordCurrent && (
                                <FormikField
                                    colWidth='col-12'
                                    component={FieldGroup}
                                    componentType='input'
                                    disabled={props.attr.isFieldDisabled}
                                    label='Current Password'
                                    name='passwordCurrent'
                                    placeholder='Enter current password'
                                    required={true}
                                    type='password'
                                    value={values.passwordCurrent}
                                />
                            )}
                            {props.attr.isFieldVisiblePasswordNew && (
                                <FormikField
                                    colWidth='col-12'
                                    component={FieldGroup}
                                    componentType='input'
                                    disabled={props.attr.isFieldDisabled}
                                    label='New Password'
                                    name='passwordNew'
                                    placeholder='Enter new password'
                                    required={true}
                                    type='password'
                                    value={values.passwordNew}
                                />
                            )}
                            {props.attr.isFieldVisiblePasswordRepeat && (
                                <FormikField
                                    colWidth='col-12'
                                    component={FieldGroup}
                                    componentType='input'
                                    disabled={props.attr.isFieldDisabled}
                                    label='Repeat Password'
                                    name='passwordRepeat'
                                    placeholder='Repeat password'
                                    required={true}
                                    type='password'
                                    value={values.passwordRepeat}
                                />
                            )}
                            {props.attr.isFieldVisiblePasswordRepeatNew && (
                                <FormikField
                                    colWidth='col-12'
                                    component={FieldGroup}
                                    componentType='input'
                                    disabled={props.attr.isFieldDisabled}
                                    label='Repeat New Password'
                                    name='passwordRepeatNew'
                                    placeholder='Repeat new password'
                                    required={true}
                                    type='password'
                                    value={values.passwordRepeatNew}
                                />
                            )}
                            <div
                                className="btn-group d-flex"
                                role="group"
                            >
                                <button
                                    onClick={props.history.goBack}
                                    type="button"
                                    className="btn btn-outline-secondary w-100"
                                >Cancel
                                </button>
                                <button
                                    type="submit"
                                    className={'btn ' + props.attr.btnColor + ' w-100'}
                                    disabled={isSubmitting}
                                >{props.attr.btnText}
                                </button>
                            </div>
                        </FormikForm>
                    </article>
                </section>
            )}
        />
    )
}

export default UserFormTemp
