// client-angular/src/app/shared/pagination/pagination.component.ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
    selector: 'app-pagination',
    templateUrl: './pagination.component.html',
    styleUrls: ['./pagination.component.css']
})
export class PaginationComponent implements OnInit {
    @Input('pagination') pagination: any;

    constructor() { }

    ngOnInit() {
    }
}

<div class="col-12">
    <ul
        *ngIf="pagination; let p"
        class="pagination"
    >
        <li [ngClass]="p.hasPrevPage ? 'page-item' : 'page-item disabled'">
            <a
                routerLink="/users/all"
                [queryParams]="{page: p.prevPage, search: p.search}"
                class="page-link"
            >Previous</a>
        </li>
        <li
            *ngFor="let i of p.totalPagesRange"
            class="page-item"
            [class.active]="i === p.currentPage"
        >
            <a
                routerLink="/users/all"
                [queryParams]="{page: i, search: p.search}"
                class="page-link"
            >{{i}}</a>
        </li>
        <li [ngClass]="p.hasNextPage ? 'page-item' : 'page-item disabled'">
            <a
                routerLink="/users/all"
                [queryParams]="{page: p.nextPage, search: p.search}"
                class="page-link"
            >Next</a>
        </li>
    </ul>
</div>

// client-react/src/components/Common/Pagination.jsx
import React from 'react'
import { Link } from 'react-router-dom'
import { withRouter } from 'react-router-dom'

const Pagination = (props) => {
    const p = props.pagination
    const li = []
    for (let i = 1; i <= p.totalPages; i++) {
        let isActive = i === p.currentPage
        li.push(
            <li key={i} className={isActive ? 'page-item active' : 'page-item'}>
                <Link to={'/admin/users/all?page=' + i + p.searchQuery} className="page-link">{i}</Link>
            </li>
        )
    }
    return (
        <div className="col-12">
            <ul className="pagination">
                <li className={p.hasPrevPage ? 'page-item' : 'page-item disabled'}>
                    <Link to={'/admin/users/all?page=' + p.prevPage + p.searchQuery} className="page-link">Previous</Link>
                </li>
                {li}
                <li className={p.hasNextPage ? 'page-item' : 'page-item disabled'}>
                    <Link to={'/admin/users/all?page=' + p.nextPage + p.searchQuery} className="page-link">Next</Link>
                </li>
            </ul>
        </div>
    )
}

export default withRouter(Pagination)
