// client-react/src/components/Movies/_MovieForm.jsx
import React from 'react'
import { Formik, Field as FormikField, Form as FormikForm } from 'formik'
import * as yup from 'yup'

import FieldGroup from '../shared/FieldGroup'

const MovieForm = ({ attr, history, initValues, params, onSubmitHandler }) => {
    return (
        <Formik
            enableReinitialize={true}
            initialValues={initValues}
            validationSchema={
                yup.object().shape({
                    imageUrl: yup.string()
                        .trim()
                        .url('Invalid url!'),
                    productionYear: yup.number()
                        .integer()
                        .min(1900, 'Production year must be min 1900')
                        .required('Production year is required!'),
                    title: yup.string()
                        .required('Title is required!')
                        .trim()
                })
            }
            onSubmit={
                async (values, { setErrors, setSubmitting }) => {
                    const id = params.id
                    const data = {
                        countries: values.countries,
                        genres: values.genres,
                        imageUrl: values.imageUrl,
                        languages: values.languages,
                        productionYear: Number(values.productionYear),
                        synopsis: values.synopsis,
                        title: values.title
                    }

                    try {
                        let res = null
                        if (!id) {
                            res = await onSubmitHandler(data)
                        } else {
                            res = await onSubmitHandler(id, data)
                        }
            
                        if (!res.success) {
                            console.log(res.message)
                            setErrors(res.errors)
                            setSubmitting(false)
                            return
                        }
            
                        history.push('/movies/all')
                    } catch (err) {
                        console.log(err)
                    }
                }
            }
            render={({ isSubmitting, values }) =>
                <section className="d-flex flex-row justify-content-center">
                    <article className="col-4">
                        <h1 className="text-center">{attr.title}</h1>
                        <FormikForm>
                            <FormikField
                                colWidth='col-12'
                                component={FieldGroup}
                                componentType='input'
                                disabled={attr.isFieldDisabled}
                                label='Title'
                                name='title'
                                placeholder='Enter title'
                                required={false}
                                type='text'
                                value={values.title}
                            />
                            <FormikField
                                colWidth='col-12'
                                component={FieldGroup}
                                componentType='input'
                                disabled={attr.isFieldDisabled}
                                label='Production Year'
                                name='productionYear'
                                placeholder='Enter production year'
                                required={false}
                                type='number'
                                value={values.productionYear}
                            />
                            <FormikField
                                colWidth='col-12'
                                component={FieldGroup}
                                componentType='input'
                                disabled={attr.isFieldDisabled}
                                label='Countries'
                                name='countries'
                                placeholder='Enter countries'
                                required={false}
                                type='text'
                                value={values.countries}
                            />
                            <FormikField
                                colWidth='col-12'
                                component={FieldGroup}
                                componentType='input'
                                disabled={attr.isFieldDisabled}
                                label='Genres'
                                name='genres'
                                placeholder='Enter genres'
                                required={false}
                                type='text'
                                value={values.genres}
                            />
                            <FormikField
                                colWidth='col-12'
                                component={FieldGroup}
                                componentType='input'
                                disabled={attr.isFieldDisabled}
                                label='Languages'
                                name='languages'
                                placeholder='Enter languages'
                                required={false}
                                type='text'
                                value={values.languages}
                            />
                            <FormikField
                                colWidth='col-12'
                                component={FieldGroup}
                                componentType='input'
                                disabled={attr.isFieldDisabled}
                                label='Image Url'
                                name='imageUrl'
                                placeholder='Enter image url'
                                required={false}
                                type='text'
                                value={values.imageUrl}
                            />
                            <FormikField
                                colWidth='col-12'
                                component={FieldGroup}
                                componentType='textarea'
                                disabled={attr.isFieldDisabled}
                                label='Synopsis'
                                name='synopsis'
                                placeholder='Enter synopsis'
                                rows='5'
                                required={false}
                                type='text'
                                value={values.synopsis}
                            />
                            <div className="btn-group d-flex" role="group">
                                <button
                                    onClick={history.goBack}
                                    type="button"
                                    className="btn btn-outline-secondary w-100"
                                >
                                    Cancel
                                </button>
                                <button
                                    type="submit"
                                    className={'btn ' + attr.btnColor + ' w-100'}
                                    disabled={isSubmitting}
                                >
                                    {attr.btnText}
                                </button>
                            </div>
                        </FormikForm>
                    </article>
                </section>
            }
        />
    )
}

export default MovieForm

// client-angular/src/app/movies/movie-form/movie-form.component.ts
import { Component, Injector, Input, OnChanges, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';

import { AbstractComponent } from '../shared/abstract.component';

const fbProps = {
    countries: {
        validators: null
    },
    genres: {
        validators: null
    },
    imageUrl: {
        validators: null
    },
    languages: {
        validators: null
    },
    productionYear: {
        min: 'Production year should be min 1900',
        required: 'Production year is required!',
        validators: Validators.compose(
            [Validators.min(1900), Validators.required]
        )
    },
    synopsis: {
        validators: null
    },
    title: {
        required: 'Title is required!',
        validators: Validators.compose(
            [Validators.required]
        )
    }
};

@Component({
    selector: 'app-movie-form',
    templateUrl: './movie-form.component.html',
    styleUrls: ['./movie-form.component.css']
})
export class MovieFormComponent extends AbstractComponent implements OnInit, OnChanges {
    @Input('attr') attr: any;
    @Input('errors') errors: any;
    @Input('formModel') formModel: Object;
    @Input('isFormReady') isFormReady: boolean;
    @Input('isSubmitting') isSubmitting: boolean;
    @Input('onSubmitHandler') onSubmitHandler: Function;
    private fbGroup = {};
    private movieForm: FormGroup;

    constructor(
        private fb: FormBuilder,
        public injector: Injector
    ) {
        super(injector);
    }

    ngOnInit() { }

    ngOnChanges() {
        // Wait for parent to collect data from service
        if (!this.isFormReady) {
            return;
        }

        this.groupFormModelPropsFromParent();

        this.movieForm = this.fb.group(this.fbGroup);

        this.subscribeToValueChangesAndValidate();
    }

    cancel() {
        this.location.back();
    }

    private groupFormModelPropsFromParent() {
        Object.keys(this.formModel)
            .forEach(key => {
                if (!fbProps.hasOwnProperty(key)) {
                    return;
                }
                this.fbGroup[key] = [
                    {
                        value: this.formModel[key],
                        disabled: this.attr.isFieldDisabled
                    },
                    fbProps[key].validators
                ];
            });
    }

    private subscribeToValueChangesAndValidate() {
        Object.keys(this.movieForm.controls).forEach(name => {
            const fieldControl = this.movieForm.get(name);
            fieldControl.valueChanges.subscribe(() => {
                if (!fieldControl.valid) {
                    this.errors[name] = Object.keys(fieldControl.errors)
                        .map(key => fbProps[name][key]);
                } else {
                    this.errors[name] = null;
                }
            });
        });
    }
}

<section class="d-flex flex-row justify-content-center">
    <article class="col-4">
        <h1 class="text-center">{{attr.title}}</h1>
        <form
            *ngIf="movieForm"
            [formGroup]="movieForm"
            (ngSubmit)="onSubmitHandler(movieForm.value)"
        >
            <div class="col-12 form-group p-0">
                <label
                    class="form-control-label"
                    for="title"
                >Title</label>
                <input
                    formControlName="title"
                    type="text"
                    class="form-control"
                    [class.is-invalid]="movieForm.get('title').touched && errors.title"
                    id="title"
                    placeholder="Enter title"
                />
                <div
                    *ngIf="movieForm.get('title').touched && errors.title"
                    class="invalid-feedback"
                >{{errors.title ? errors.title : 'Title is Required!'}}</div>
            </div>
            <div class="col-12 form-group p-0">
                <label
                    class="form-control-label"
                    for="productionYear"
                >Production Year</label>
                <input
                    formControlName="productionYear"
                    type="number"
                    class="form-control"
                    [class.is-invalid]="movieForm.get('productionYear').touched && errors.productionYear"
                    id="productionYear"
                    placeholder="Enter production year"
                />
                <div
                    *ngIf="movieForm.get('productionYear').touched && errors.productionYear"
                    class="invalid-feedback"
                >{{errors.productionYear ? errors.productionYear : 'Production year is Required!'}}</div>
            </div>
            <div class="col-12 form-group p-0">
                <label
                    class="form-control-label"
                    for="countries"
                >Countries</label>
                <input
                    formControlName="countries"
                    type="text"
                    class="form-control"
                    id="countries"
                    placeholder="Enter countries"
                />
            </div>
            <div class="col-12 form-group p-0">
                <label
                    class="form-control-label"
                    for="genres"
                >Genres</label>
                <input
                    formControlName="genres"
                    type="text"
                    class="form-control"
                    id="genres"
                    placeholder="Enter genres"
                />
            </div>
            <div class="col-12 form-group p-0">
                <label
                    class="form-control-label"
                    for="languages"
                >Languages</label>
                <input
                    formControlName="languages"
                    type="text"
                    class="form-control"
                    id="languages"
                    placeholder="Enter languages"
                />
            </div>
            <div class="col-12 form-group p-0">
                <label
                    class="form-control-label"
                    for="imageUrl"
                >Image Url</label>
                <input
                    formControlName="imageUrl"
                    type="url"
                    class="form-control"
                    id="imageUrl"
                    placeholder="Enter image url"
                />
            </div>
            <div class="col-12 form-group p-0">
                <label
                    class="form-control-label"
                    for="synopsis"
                >Synopsis</label>
                <textarea
                    formControlName="synopsis"
                    type="text"
                    class="form-control"
                    id="synopsis"
                    placeholder="Enter synopsis"
                    rows="5"
                ></textarea>
            </div>
            <div
                class="btn-group d-flex"
                role="group"
            >
                <button
                    (click)="cancel()"
                    type="button"
                    class="btn btn-outline-secondary w-100"
                >Cancel</button>
                <button
                    type="submit"
                    class="btn {{attr.btnColor}} w-100"
                    [disabled]="movieForm.invalid || isSubmitting"
                >{{attr.btnText}}</button>
            </div>
        </form>
    </article>
</section>
